site_name: PulseDocs
theme: 
    name: material
pages:
    - Home: index.md
    - Stuypulse Lib: stuylib/index.md
    - Tutorials:
        - Home: tutorials/index.md
        - CV:
            - Home: cv/index.md
            - Setting up OpenCV and stuyvision for Windows + Linux: cv/setup.md
            - Setting up OpenCV and stuyvision for Mac: tutorials/cv/mac-setup.md
            - Camera Setup: tutorials/cv/camera-setup.md
            - Vision and Tuning: tutorials/cv/vision-and-tuning.md
            - "Walkthrough: Blur, Erode, Dilate": tutorials/cv/walkthrough-blur-erode-dilate.md
            - NVIDIA Jetson: tutorials/cv/jetson.md
            - Miscellaneous Issues with CV: tutorials/cv/misc.md
            - Motion profiling: tutorials/cv/motion-profiling.md

        - Autonomous Routines:
            - Mobility Auton: tutorials/autons/mobility.md
    - Newbie Education:
            - Home: newbie-edu/index.md
            - 2018 Review: newbie-edu/2018-edu.md
    - The Vault:
        - Home: vault/index.md
        - Radios: vault/radios.md
        - Competition: vault/competition.md
        - Roborio: vault/roborio.md
        - JRE: vault/jre.md
